name: '🧰 Node Environment Setup'
description: 'Sets up Node.js with pnpm and optional caching for Nx projects'
author: 'Terry Lee Allen, Jr'

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'
  pnpm-version:
    description: 'PNPM version'
    required: false
    default: '10.6.4'
  cache-version:
    description: 'Manual cache invalidation key'
    required: false
    default: 'v1'
  skip-summary:
    description: 'Skip environment dashboard and GitHub step summary'
    required: false
    default: 'false'

outputs:
  pnpm-version:
    description: 'PNPM version'
    value: ${{ inputs.pnpm-version }}
  node-version:
    description: 'Node.js version'
    value: ${{ inputs.node-version }}
  cache-key:
    description: 'Generated cache key'
    value: ${{ steps.cache-key.outputs.key }}

runs:
  using: 'composite'
  steps:
    - name: 📦 Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}

    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: 🔑 Generate versioned cache key
      id: cache-key
      shell: bash
      run: |
        set -euo pipefail

        echo "🔄 Generating versioned cache key..."
        NODE_VERSION="${{ inputs.node-version }}"
        PNPM_VERSION="${{ inputs.pnpm-version }}"
        CACHE_VERSION="${{ inputs.cache-version }}"
        LOCK_HASH=$(sha256sum pnpm-lock.yaml | cut -d ' ' -f1)

        CACHE_KEY="${CACHE_VERSION}-node${NODE_VERSION}-pnpm${PNPM_VERSION}-deps-${LOCK_HASH:0:8}"
        echo "key=${CACHE_KEY}" >> $GITHUB_OUTPUT

    - name: 📚 Restore Dependency Cache
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ steps.cache-key.outputs.key }}

    - name: 📥 Install Dependencies (if cache miss)
      if: steps.cache-deps.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "📦 Dependency cache miss. Installing with pnpm..."
        pnpm install --frozen-lockfile
        echo "✅ Dependencies installed successfully."

    - name: 📊 Environment Summary
      if: inputs.skip-summary != 'true'
      shell: bash
      env:
        NODE_VERSION: ${{ inputs.node-version }}
        PNPM_VERSION: ${{ inputs.pnpm-version }}
        CACHE_HIT: ${{ steps.cache-deps.outputs.cache-hit || 'false' }}
        CACHE_KEY: ${{ steps.cache-key.outputs.key }}

      run: |
        echo "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
        echo "┃                        🧰 NODE ENVIRONMENT SETUP                      ┃"
        echo "┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫"
        echo "┃ • Node.js Version: ${NODE_VERSION}                                    "
        echo "┃ • PNPM Version:    ${PNPM_VERSION}                                    "
        echo "┃ • Cache Hit:       ${CACHE_HIT}                                       "
        echo "┃ • Cache Key:       ${CACHE_KEY}                                    "
        echo "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛"

        echo "## 🧰 Node Environment Setup Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Node.js Version:** ${NODE_VERSION}" >> $GITHUB_STEP_SUMMARY
        echo "- **PNPM Version:** ${PNPM_VERSION}" >> $GITHUB_STEP_SUMMARY
        echo "- **Cache Hit:** \`$CACHE_HIT\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Cache Key:** \`$CACHE_KEY\`" >> $GITHUB_STEP_SUMMARY

